development:
  adapter: postgresql
  database: beer_fridge_development

test:
  adapter: postgresql
  database: beer_fridge_test

production:
  adapter: postgresql
  encoding: unicode
  database: beer_fridge_production